const API = {
  BASE_URL: "https://piccocabs-server-46642b82a774.herokuapp.com",
  // BASE_URL: "http://localhost:8080",

  // GET_ALL_BOOKINGS: "/Booking/booking",
  GET_ALL_BOOKINGS: "/Booking/",
  DELETE_ALL_BOOKING: "/Booking/",
  GET_BOOKING_ATTEMPT: "/booking-attempt/BookingAttempt",
  GET_OFFERS: "/Offers/Offer",
  DELETE_BOOKING_ATTEMPT: "/booking-attempt/",
  GET_DRIVER: "/Driver/",
  DELETE_DRIVER: "/Driver/",
  GET_DRIVER_LOCATION: "/Driver/location",
  // GET_CARS: "/Cars/",
  GET_CARS_DETAILS: "/Cars/Details",
  GET_BOOKING_CANCELLEDTRIPS: "/Booking/cancelledTrips",
  GET_BOOKING_TRIPCOMPLETED: "/Booking/tripCompleted",
  GET_PICKUP_LOCATION: "/Pickuplocation/location",
  DELETE_PICKUP_LOCATION: "/Pickuplocation/",
  GET_LOGIN_ATTEMPTS: "/Loginattempts/get",
  CREATE_BOOKING: "/Booking",
  CREATE_CARS: "/Cars",
  DELETE_CARS: "/Cars/",
  CREATE_DRIVER: "/Driver",
  CREATE_PICKUP_LOCATION: "/Pickuplocation",
  CREATE_OFFERS: "/Offers",
  DELETE_OFFERS: "/Offers/",
  GET_BOOKING_ONGOING: "/Booking/ongoing",
  GET_USER: "/User/get",
  CREATE_BOOKINGATTEMPT: "/booking-attempt",
  CREATE_LOGINATTEMPTS: "/Loginattempts",
  CREATE_USER_FIND: "/User/find-by-number",

  UPDATE_ALL_BOOKING: "/Booking/",
  UPDATE_DRIVER: "/Driver/",
  UPDATE_CARS: "/Cars/",
  UPDATE_PICKUP_LOCATION: "/Pickuplocation/",
};

export default API;
